version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
    - ome
  ome:
    image: "airensoft/ovenmediaengine:0.14.15"
    ports:
      - "1935:1935"
      - "4000:4000/udp"
      - "3333:3333"
      - "3334:3334"
      - "3478:3478"
      - "9000:9000"
      - "9999:9999/udp"